// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPh2OHZQ0oozfx8cg-4ZAznJVkn0owQM0',
    appId: '1:190539958945:web:74bedd0530a2e9673a7ee0',
    messagingSenderId: '190539958945',
    projectId: 'jubu-9d725',
    authDomain: 'jubu-9d725.firebaseapp.com',
    storageBucket: 'jubu-9d725.firebasestorage.app',
    measurementId: 'G-M5V9CV69WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDB2CUghoNBwVnnPcR_IsFqPptN8NFpJo',
    appId: '1:190539958945:android:e1b061663e2470123a7ee0',
    messagingSenderId: '190539958945',
    projectId: 'jubu-9d725',
    storageBucket: 'jubu-9d725.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NdkHvRYmGhHNSraSorSj7Jf5ng8e-TU',
    appId: '1:190539958945:ios:5c368ea9fa6da5c53a7ee0',
    messagingSenderId: '190539958945',
    projectId: 'jubu-9d725',
    storageBucket: 'jubu-9d725.firebasestorage.app',
    iosClientId:
        '190539958945-6k657jdvan2bc96mk6ih9bma5j0l81a5.apps.googleusercontent.com',
    iosBundleId: 'com.chulminator.jubu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPh2OHZQ0oozfx8cg-4ZAznJVkn0owQM0',
    appId: '1:190539958945:web:a86148da65a0202c3a7ee0',
    messagingSenderId: '190539958945',
    projectId: 'jubu-9d725',
    authDomain: 'jubu-9d725.firebaseapp.com',
    storageBucket: 'jubu-9d725.firebasestorage.app',
    measurementId: 'G-GJK3N21BQ1',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NdkHvRYmGhHNSraSorSj7Jf5ng8e-TU',
    appId: '1:190539958945:ios:5c368ea9fa6da5c53a7ee0',
    messagingSenderId: '190539958945',
    projectId: 'jubu-9d725',
    storageBucket: 'jubu-9d725.firebasestorage.app',
    iosClientId:
        '190539958945-6k657jdvan2bc96mk6ih9bma5j0l81a5.apps.googleusercontent.com',
    iosBundleId: 'com.chulminator.jubu',
  );
}
